version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: d_jenkins.Dockerfile
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - ./tests:/tests
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium
    restart: always

  selenium:
    build:
      context: .
      dockerfile: d_selenium.Dockerfile
    ports:
      - "5900:5900"
    volumes:
      - ./ui/tests:/tests
    command: tail -F /dev/null

volumes:
  jenkins_home: