---
name: Testing of report creation
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pull-requests: write
  checks: write
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report.xml
